### ISSUE TITLE
Clientside Crash - 1.12.2 - Forge 14.23.1.2590

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJty/RFToolsDimensions#186] opened 2018-01-18 14:14 UTC
Client Early Startup
https://gist.github.com/P3rf3ctXZer0/142b907e5d9545e02099fe4835fcf0be

Crash Log
https://gist.github.com/P3rf3ctXZer0/19694a2765265bbb31ede5ab03fb45b8

Remember newer logs include modname and version etc.

**Comment by McJty** [comment] 2018-01-18 14:37
What were you doing when this crash happened?

**Comment by P3rf3ctXZer0** [comment] 2018-01-18 14:37
Starting the game Ironically dedicated server didn't crash just client I tried client 3 times did client-side code change in newest forge? I know JEI dev requested some additional client forge functionality ... try running build against latest forge.

**Comment by McJty** [comment] 2018-01-18 14:39
Hmm strange. Exactly this version of rftools dimensions is included in many packs with no problems. I wonder if there is some kind of mod interaction. Is this a custom pack?

**Comment by P3rf3ctXZer0** [comment] 2018-01-18 14:40
Yeah very custom ... I will run some tests later to see if I can break it down. I mean honestly the mod is awesome but I won't melt if I cannot use it. I do have Simple Dimensions by @Lumien231 so I can create a lot of farming dimensions.

**Comment by josephcsible** [comment] 2018-01-18 15:21
Duplicate of #181. It's Dimensional Doors' fault; see DimensionalDevelopment/DimDoors#20.

**Closed as completed by josephcsible** 2018-01-18 15:21 UTC
