### ISSUE TITLE
Single player Crash

### ISSUE THREAD

**Issue by Gamingdaredevil** [McJty/RFToolsDimensions#268] opened 2019-07-15 14:02 UTC
Issue description: 
MC Crashes when making/ entering a single player world after being on a server with a RFTools dimension

Steps to reproduce: 
Install below mods on server and client, join the server make a RFTools dimensions go to to the new dimensions then leave server. Make/ enter a single player save and then game will crash. doesn't happen after being on a server without RFTools dimensions in the save.

Versions:
Minecraft:1.12.2
Forge:14.23.5.2838
McJtyLib:1.12-3.5.3
RFTools:1.12-7.71
RFToolsCtrl:-1.12-2.0.2
RFToolSdim:1.12-5.71
RFToolSpower:1.12-1.2.0
Possibly incompatible mods and versions:Only mods listed above.

Crash : https://pastebin.com/QvK9yWKn

**Comment by josephcsible** [comment] 2019-07-15 14:19
Duplicate of #205

**Closed as completed by josephcsible** 2019-07-15 14:19 UTC
