### ISSUE TITLE
Crash when creating dimension

### ISSUE THREAD

**Issue by bdew** [McJty/RFToolsDimensions#80] opened 2017-02-03 14:41 UTC
Crashed as dimension building was completed. After restarting the dimension wasn't usable (missing dimension data). I've deleted the bugged dimension and re-created it without crashing, but it didn't get the extra random mob entries the second time, which might be related.

Crash report: https://gist.github.com/bdew/5699271fc07dbe7927b3b0f0df1610ce

Info of the dimension being created: https://gist.github.com/bdew/7c402e884ca87fa81cfe1eca01a3a1f6 (this was taken after the restart)

**Comment by McJty** [comment] 2017-02-03 14:46
I'm checking it out. Thanks for the report

**Comment by McJty** [comment] 2017-02-03 14:56
This is very weird. The code for Biome.SpawnListEntry has nothing to 'null-pointer-except' on. I don't understand how this can even happen. Suggestions are welcome

**Comment by McJty** [comment] 2017-02-03 18:43
I found out the cause. Will be fixed next release

**Closed as completed by McJty** 2017-02-03 18:43 UTC

**Comment by bdew** [comment] 2017-02-03 19:57
Out of curiosity... what was it? Because looking at SpawnListEntry i don't see it either.

**Comment by McJty** [comment] 2017-02-03 21:20
Apparently entityClass was null and if you update forge in the dev env there is apparently some new forge added code that does something with that class. I missed that because my forge was older
