### ISSUE TITLE
Repeat of Issue #17 in 1.10.2

### ISSUE THREAD

**Issue by Khazadir** [McJty/RFToolsDimensions#31] opened 2016-09-04 14:47 UTC
I'm seeing the same problem listed in the (closed) issue #17. 

 I am running rftoolsdim-1.10-4.30beta48 and I cannot use a dialing device to dial away from any world with any non-random world.  If I try dialing anywhere in a created world with a dimlet assigned, i get the issue listed in issue #17.

Any advice?

**Comment by McJty** [comment] 2016-09-04 16:50
Can you give me logs?

**Comment by Khazadir** [comment] 2016-09-04 18:43
I can try.

I don't see anything weird in the game other than I can't dial away from a non-random world.  It's not a crash or anything.

How would I go about getting a log you can use?

**Comment by Khazadir** [comment] 2016-09-04 19:16
More information: I'm getting Journeymap Corruption of my homeworld.  This only occurs on the worlds that are specific; the random one doesn't have this issue.  Also, these worlds tend to be highly corrupted...

Also, whenever I try to make a 'random' world (i.e. put a blank grid into the Enscriber and hit Store), I always get a copy of my original random world.  Don't know if any of this helps...

**Comment by Khazadir** [comment] 2016-09-05 11:54
More information: It's not that Journeymap is being corrupted, my World is being corrupted.  I made a Prismarine Normal Terrain world, went through, and couldn't come back.   My JourneyMap was overwriting my Overworld map as I explored.  Killed myself and came back in the Overworld, and the Overworld itself was showing the Prismarine landscape until I got close enough for it to fix itself.

I'm beginning to wonder if something is making the dimensions all think they are dimension 0.  Also, when trying to select a destination in the created worlds, when selecting my home base location (dimension: Overworld), I get a numerical distance and not a 'dimensional warp' reading for distance.

Hope this helps!

**Comment by Khazadir** [comment] 2016-09-05 12:00
Ok, found out a way to fix it.

Apparently, using Realistic Terrain Generation (mod) causes issues unless you set the World-specific config up correctly.  

For others help:  Go into your World folder, World Specific configuration folder, GeographiCraft folder, CCDimesnions file.

Change the include dimensions from 0 to *.  

Thank you for your patience with me.

**Comment by Khazadir** [comment] 2016-09-06 02:20
Happened again.

This time it was a dimlet with Time:Noon and Material:Glass modifying Terrain: Normal.  Got some random items (ovoids with liquid in them).

I went in, and I couldn't dial the home dimension.  Also had world confusion.

Ironically, my wife who also plays on the server, COULD dial the home dimension and got us both out.  Also, on my screen, night was falling, but on hers, it was still noon.

Lastly, I'm hosting the server on the same machine I am playing on.

**Comment by cylek56** [comment] 2016-09-14 07:13
Same here on a dedicated server (Aratfat's one).
Here's the logs on client:
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist
    at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:132) ~[DimensionManager.class:?]
    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:282) ~[DimensionManager.class:?]
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:63) ~[bln.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:1014) ~[bll.class:?]
    at net.minecraft.network.play.server.SPacketRespawn.func_148833_a(SourceFile:31) ~[hj.class:?]
    at net.minecraft.network.play.server.SPacketRespawn.func_148833_a(SourceFile:12) ~[hj.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
    ... 9 more

**Comment by McJty** [comment] 2016-09-27 09:59
This should be fixed since last release (version 50)

**Closed as completed by McJty** 2016-09-27 09:59 UTC
