### ISSUE TITLE
Crash with Dimensional Doors beta

### ISSUE THREAD

**Issue by djnifos** [McJty/RFToolsDimensions#182] opened 2018-01-07 21:12 UTC
[https://pastebin.com/Yvn1xU7j](https://pastebin.com/Yvn1xU7j)

Crash during loading.  Going to post it over there too, since the pack was loading fine until I added Dimensional Doors, but as a heads up, here you go.

**Comment by josephcsible** [comment] 2018-01-07 21:14
Duplicate of #181

**Closed as completed by josephcsible** 2018-01-07 21:14 UTC
Labels: duplicate, Maybe Other Mods Bug
