### ISSUE TITLE
crashed on creating dimension. 

### ISSUE THREAD

**Issue by devilishhero** [McJty/RFToolsDimensions#241] opened 2018-10-24 14:28 UTC
Issue description: crashed on creating dimension. 

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:1.12-3.0.6
* RFTools:1.12-7.56
* RFTools Dimensions: 1.12-5.61

Possibly incompatible mods: 

Relevant logs, if any: crash on re-opening world: https://pastebin.com/sw5HY3xU crash on creating dimension: https://pastebin.com/QucUe1Qb

**Comment by McJty** [comment] 2018-10-24 14:39
What kind of dimension is it? Can you get in game if you edit your player out of the dimension?

**Comment by devilishhero** [comment] 2018-10-24 18:44
random dimension.  and im sure i could. but i dont have a tool to do that. it crashed as soon as i walk in to the portal.

**Comment by josephcsible** [comment] 2018-10-24 23:16
Duplicate of #238

**Closed as completed by josephcsible** 2018-10-24 23:16 UTC
