### ISSUE TITLE
Cubic Chunks equals not gonna start.

### ISSUE THREAD

**Issue by border999** [McJty/RFToolsDimensions#187] opened 2018-01-20 06:12 UTC
Gets right to when the game should start. Crashes.
https://pastebin.com/ZH4nQFmR

**Comment by josephcsible** [comment] 2018-01-20 14:09
Duplicate of #181. It's Dimensional Doors' fault; see DimensionalDevelopment/DimDoors#20.

**Closed as completed by josephcsible** 2018-01-20 14:09 UTC
