### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Xiaminou** [McJty/RFToolsDimensions#43] opened 2016-10-12 12:32 UTC
I have been living in an RFTools Dimension for quite some time now. It was working fine yesterday but today I get a crash when I try to start my server.

Crash Report: http://pastebin.com/0WsxnXiL
Log: [fml-server-latest.txt](https://github.com/McJty/RFToolsDimensions/files/524451/fml-server-latest.txt)

**Comment by McJty** [comment] 2016-10-12 12:34
Did you update any mods? Anything significant changed?

**Comment by McJty** [comment] 2016-10-12 12:35
Seems somehow dimension 4 got lost:
[14:23:44] [Server thread/INFO] [STDERR/]: [net.minecraftforge.common.DimensionManager:initDimension:223]: Cannot Hotload Dim: Could not get provider type for dimension 4, does not exist

**Comment by McJty** [comment] 2016-10-12 12:35
Did you update or change pams harvestcraft?

**Comment by Xiaminou** [comment] 2016-10-12 12:40
Well before yesterday I was taking a break for about a month, so yesterday I updated 30+ mods, and added some more.
Pam's harvestcraft was among them, yes.

**Comment by McJty** [comment] 2016-10-12 12:40
Problem is that the dimension was generated with something specific from pam's harvestcraft that no longer exists. I will see if I can add some protection for that to avoid the crash

**Comment by Xiaminou** [comment] 2016-10-12 12:49
Interesting, yesterday, when I launched the server for the first time after updating everything it should have delete all those items when forge prompted for it.

**Comment by McJty** [comment] 2016-10-12 12:52
yes but that's not the problem. The problem is that rftools dimension itself also keeps information and stores its as block ids. If too much changes the ids can change and this is probably what happened. I'll see what I can do about this

**Comment by McJty** [comment] 2016-10-12 13:52
I made a fix which will hopefully make your world loadable again. I am not able to test this though.
Also made the code more robust so that for new dimensions this should no longer occur. Will release fix for this shortly

**Closed as completed by McJty** 2016-10-12 13:52 UTC

**Comment by Xiaminou** [comment] 2016-10-12 14:13
Perfect, it works! thank you.

**Comment by Xiaminou** [comment] 2016-10-12 14:25
Scratch that, it messed up the IDs:
![2016-10-12_16 24 07](https://cloud.githubusercontent.com/assets/8670392/19313899/69ac766c-9098-11e6-988a-3ac4fdf2105d.png)

**Comment by Xiaminou** [comment] 2016-10-12 14:40
Okay, I tried using a backup of the world from yesterday with this new version of RFTools dimensions and it didn't mess up the IDs, which means it was something else that corrupted my old world.
This is all too weird, I have no idea what's happening anymore. I'm afraid it will bug once again when I close the server.
![2016-10-12_16 38 36](https://cloud.githubusercontent.com/assets/8670392/19314482/8f66556a-909a-11e6-98bf-51ec3fe05f6a.png)

**Comment by Xiaminou** [comment] 2016-10-12 14:44
Yep, the server crashed when I tried to close it: 
[fml-server-latest.txt](https://github.com/McJty/RFToolsDimensions/files/524832/fml-server-latest.txt)

This might be what happened the first time, I didn't exactly pay attention last time I closed the server, it might have crashed like this which is what would have triggered the whole mess of IDs.
Yep, after starting the server once more, it's definitely happening again.

**Comment by Xiaminou** [comment] 2016-10-12 14:49
Now I still have no idea what's actually causing the crash when closing the server, I am looking at the log but I'd lie if I said I understood half of it, I have to ask for your help once more, could you point me in the right direction?

**Comment by McJty** [comment] 2016-10-12 17:11
I let @elec332 look at this as it seems to be caused by eleccore

**Comment by McJty** [comment] 2016-10-17 17:11
Is this solved now with latest ElecCore?
