### ISSUE TITLE
Terrain and Feature Dimlets Do Not Spawn

### ISSUE THREAD

**Issue by Etezzer** [McJty/RFToolsDimensions#321] opened 2021-03-06 17:55 UTC
Issue description: After creating multiple random dimensions and flying around to find the RF Dimensions buildings no terrain and no feature dimlets have spawned in the chests.

Steps to reproduce: Create new dimension fly to RF Dimensions buildings, no terrain and no feature dimlets have spawned.

Versions:
* Minecraft: 1.16
* Forge: 36.0.45
* CompatLayer (only if on Minecraft 1.10 or 1.11):N/A (Minecraft version 1.16)
* McJtyLib: 1.16-5.0.17.jar
* RFTools:
*             Base: 1.16-2.0.20.jar
*             Builder: 1.16-3.0.15.jar
*             Control: 1.16-4.0.7.jar
*             Storage: 1.16-2.0.11.jar
*             Utility: 1.16-3.0.23.jar
* RFTools Dimensions: 1.16-7.0.4-beta.jar

Possibly incompatible mods: Unsure.

Relevant logs, if any: N/A (no crash report)

**Comment by McJty** [comment] 2021-03-06 18:04
They do spawn. I've seen them. The problem is that there are many more material dimlets so the chance of a terrain or feature dimlet is small. I'll try to find a way to distribute it more evenly per type

**Comment by Etezzer** [comment] 2021-03-06 18:28
Thank you! At least I can keep looking. I just haven't seen either one and I've spent 6hrs playing the new Direwolf20 pack today.

**Comment by theLadyStardust** [comment] 2021-03-09 20:26
I had the same issue, maybe you could have a way to determine the type of dimlet in the researcher?

**Comment by McJty** [comment] 2021-03-14 04:37
There was a problem with the random generation of dimlet hut loot. Will be fixed next release

**Closed as completed by McJty** 2021-03-14 04:37 UTC
