### ISSUE TITLE
Crash when in rftools dimension

### ISSUE THREAD

**Issue by RiftomeR** [McJty/RFToolsDimensions#228] opened 2018-07-03 15:38 UTC
Issue description: 
I was in newly created rftools dimension and my minecraft has crashed.

Steps to reproduce: 
Create rftools dimensions with cavern terrain of netherrack and with lakes of lava, hell biome, oregen, orbs of sandstone, cave spiders, ghasts, blazes, weakness 1 and mining slowdown 3. Enter into it and fly around. 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2709
* McJtyLib: 3.0.2
* RFTools: 7.54
* RFTools Dimensions: 5.60

Possibly incompatible mods: 
OptiFine

Relevant logs, if any: 
[Crash report](https://pastebin.com/YR4CrUa6)

**Comment by McJty** [comment] 2018-07-03 18:50
Hmm looks like some mob is trying to spawn there and failing. What other mods do you have?

**Comment by josephcsible** [comment] 2018-07-04 19:01
Can you replace your RFTools Dimensions jar with [this one](https://github.com/josephcsible/RFToolsDimensions/releases/download/5.60-mobsanitycheck/rftoolsdim-1.12-5.60-mobsanitycheck.jar), and then post your new crash report?

**Comment by RiftomeR** [comment] 2018-07-16 08:21
Unfortunately, i have deleted this world and can't reproduce this crash anymore.
[Link to full mod list.](https://rawgit.com/AllTheMods/ATM-3/master/modlist.html)

**Comment by josephcsible** [comment] 2018-07-16 11:45
I'm going to close this then, since I have no way of reproducing this either. If it ever happens again, just post here and I'll reopen it.

**Closed as completed by josephcsible** 2018-07-16 11:45 UTC
