### ISSUE TITLE
Cannot find dimlet huts in ATM 8, 1.19.2

### ISSUE THREAD

**Issue by Mrwimz** [McJty/RFToolsDimensions#424] opened 2022-12-14 11:39 UTC
Issue description: Dimlet huts non existent

Steps to reproduce: Create a dimension in 1.19.2, i've personally made 50 without finding a single dimlet hut, to get some lost knowledge?, it this just me?

Versions:
* Minecraft: 1.19.2
* Forge: 43.1.55
* McJtyLib: 1.19-7.0.6
* RFTools: 1.19.1-4.0.3
* RFTools Dimensions: 1.19-9.0.2

**Comment by McJty** [comment] 2022-12-14 11:43
I'll check it out. I have an idea what might be wrong

**Comment by McJty** [comment] 2022-12-14 17:39
Hmm no theory doesn't match. I cannot reproduce this. For me these huts do appear. Weird...

**Comment by Mrwimz** [comment] 2022-12-14 17:54
Must have something to do with ATM 8, do you have any ideas, what could cause the incompatability? + Just updated the config, where you can adjust spawn chances of dimlet hus. Updated to 1.0, so 1 dimlet per chunk and still no huts -_-

**Comment by Mrwimz** [comment] 2022-12-14 18:56
Also, i don't have any trees or decorations of any shape or form in my dimensions, that might be a correletation?, I noticed you mentioned something about terraBlender aswell.

**Comment by McJty** [comment] 2022-12-15 05:23
There was a bug with terrablender some time ago. But that should have been fixed now... Make sure everything is up to date

**Comment by ESBL-Erik** [comment] 2022-12-18 12:33
I've encountered the exact same problem on my custom mod pack for 1.19.2. 
After removing Biomesoplenty and Terrablender, the dimlet huts returned and so did the trees and decorations.

All RFTools and biomesop and Terrablender were running latest versions available.

**Comment by McJty** [comment] 2022-12-18 13:00
Sigh, that means that mod is still messing with structures...

**Comment by McJty** [comment] 2022-12-18 13:03
Can you please report this on the BoP/terrablender github?

**Comment by McJty** [comment] 2022-12-19 06:08
It was on my side. I think the latest version fixes it

**Comment by ESBL-Erik** [comment] 2022-12-19 09:00
Sorry mate, but it seems that it's not fixed. 

Some more background: If i make a flat world with digits 1 2 3 4 (from your /rftoolsdim quicksetup command) and i teleport to this world, i get a flat world. I spawn at Y:66 but i have to dig myself up to Y:120. This is where land level is. There are animals, but no trees or other decorations and there is no dimlet hut to be found. 
The same happens when i make a normal world, except ofcourse the terrain is then... normal :-)

This is after i add Biomesoplenty and Terrablender.

If i disable biomeoplenty and leave terrablender enabled, the same problem occurs.

If i disable terrablender, on a flat terrain. I spawn at Y:120, but this time i spawn on a nice slab of dimensional blocks, these are missing in the problem scenario. Trees spawn, huts spawn, but i see no animals. 
If i use a normal terrain, i spawn at a lower Y (71 in this case) and i see huts, trees, decorations and animals.

If you need more testing, let me know.

**Comment by ESBL-Erik** [comment] 2022-12-19 09:18
If you need any testing, just let me know :-)

**Comment by McJty** [comment] 2022-12-19 10:42
It's apparently a problem in TerraBlender. There is a new build for 1.19.2 of TerraBlender. Can you test with that version?

**Comment by ESBL-Erik** [comment] 2022-12-19 10:45
I just saw it. Was already uploading to start testing. will report.

**Comment by ESBL-Erik** [comment] 2022-12-19 10:51
The Terrablender update seems to FIX the issue! :-)

Sorry for bothering you with it, @McJty. Kudos for your work and support!

**Closed as completed** 2022-12-19 10:51 UTC

**Comment by Mrwimz** [comment] 2022-12-19 10:53
Thanks for investigating this issue, much respect to both of you :)

**Comment by ESBL-Erik** [comment] 2022-12-19 11:07
Just a small follow-up (FYI): I have done some more testing and it's not fully fixed yet. Only the default minecraft biomes will work as expected. A BOP biome will still exhibit the same problems. But I think we can be confident that the problem lies with Terrablender, so i will continue there :-)

**Comment by sharkck** [comment] 2023-02-14 03:41
Have there been any updates to this?  I'm running a custom modpack myself and I've generated 10 worlds so-far and none have spawned in any dimlet buildings.

**Comment by McJty** [comment] 2023-02-14 04:54
Make sure to update terrablender. That should fix it. At least for default biomes

**Comment by sharkck** [comment] 2023-02-14 20:17
I found the beta update for terrablender... unfortunately it only works for default.  I cannot create a void dimension :(

**Comment by sharkck** [comment] 2023-02-16 02:58
So far the only response on this I've gotten is:
**Adubbz — Yesterday at 10:46 PM
RFTools probably isn’t adding modded biomes to the possible biomes list in its dimension if I had to guess off the top of my head 
(That’d have to be done on their side)**

**Comment by sharkck** [comment] 2023-02-16 14:30
Here is the "final" update for now from the Terrablender team:
As mentioned on Discord, this would likely be because modded biomes aren’t being added to their possible biomes list in their biome source. TerraBlender is able to do this itself with Vanilla’s biome source, but not theirs given they are created at runtime. Accordingly, this will need to be handled on their side.

With the above in mind, I’m going to close this, since I don’t believe it can be resolved on TerraBlender’s side.

**Comment by sharkck** [comment] 2023-02-16 14:30
Should I create a new issue or can this be re-opened?
